<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Audit logs · UIU Recruitment Portal Admin</title>
  <?php $adminSection = 'audit'; ?><?= $this->include('admin/_styles') ?>
  <style>.audit-filters{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:20px}.audit-filters input,.audit-filters select{height:38px;border:1px solid #dfe4ec;border-radius:8px;padding:0 10px;background:#fff;font:inherit}.filter-actions{display:flex;gap:8px;align-items:center}.filter-actions button{height:38px;border:0;border-radius:8px;padding:0 15px;background:#168fd4;color:#fff;font-weight:600}.filter-actions a{color:#168fd4;font-size:13px}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef8ff;color:#1769aa;font-size:11px;font-weight:700}.muted{color:#798196;font-size:12px}.pager{display:flex;justify-content:space-between;align-items:center;margin-top:16px;color:#69778d;font-size:13px}.pager a{color:#168fd4;font-weight:700;margin-left:12px}@media(max-width:900px){.audit-filters{grid-template-columns:repeat(2,1fr)}}@media(max-width:550px){.audit-filters{grid-template-columns:1fr}}\n+  </style>
</head>
<body><div class="admin-app"><?php $username=session()->get('admin_username');$usertype=session()->get('admin_usertype'); ?><?= $this->include('admin/_sidebar') ?><main class="admin-main"><header class="admin-topbar"><div class="admin-top-title">Audit logs</div><div class="admin-search">⌕ <span>Search...</span><span style="margin-left:auto">⌘ K</span></div><div class="admin-pill">✦ Audit trail</div></header><div class="admin-content">
  <div class="admin-heading"><div><h1>Audit logs</h1><p>Append-only security, submission, and administrative activity.</p></div><a class="admin-btn" href="<?= site_url('admin/login-history') ?>">Login history</a></div>
  <form class="audit-filters" method="get" action="<?= site_url('admin/audit-logs') ?>">
    <input type="date" name="date_from" value="<?= esc($filters['date_from']) ?>" aria-label="Date from"><input type="date" name="date_to" value="<?= esc($filters['date_to']) ?>" aria-label="Date to">
    <select name="event"><option value="">All events</option><?php foreach ($events as $event): ?><option value="<?= esc($event['event']) ?>" <?= $filters['event'] === $event['event'] ? 'selected' : '' ?>><?= esc($event['event']) ?></option><?php endforeach; ?></select>
    <input name="user" placeholder="User / actor" value="<?= esc($filters['user']) ?>"><input name="reference" placeholder="Reference or entity ID" value="<?= esc($filters['reference']) ?>"><input name="ip" placeholder="IP address" value="<?= esc($filters['ip']) ?>"><select name="device"><option value="">All devices</option><?php foreach (['Desktop','Mobile','Tablet','Bot','Unknown'] as $device): ?><option value="<?= $device ?>" <?= $filters['device'] === $device ? 'selected' : '' ?>><?= $device ?></option><?php endforeach; ?></select><input name="browser" placeholder="Browser" value="<?= esc($filters['browser']) ?>"><div class="filter-actions"><button type="submit">Search</button><a href="<?= site_url('admin/audit-logs') ?>">Reset</a></div>
  </form>
  <?php if (!$logs): ?><div class="admin-card admin-empty">No audit events found.</div><?php else: ?><div class="admin-table"><table><thead><tr><th>Date &amp; time</th><th>User / actor</th><th>Event</th><th>Entity / reference</th><th>IP address</th><th>Device</th><th>Action</th></tr></thead><tbody><?php foreach ($logs as $log): ?><tr><td><?= esc(date('d M Y · h:i:s A', strtotime($log['created_at']))) ?></td><td><strong><?= esc($log['actor_name'] ?: ($log['actor_username'] ?: ($log['user_id'] ? 'User #' . $log['user_id'] : 'System'))) ?></strong></td><td><span class="badge"><?= esc($log['event']) ?></span></td><td><?= esc($log['reference'] ?: '—') ?><br><span class="muted"><?= esc($log['entity_type'] ?: '') ?></span></td><td><?= esc($log['ip_address'] ?: '—') ?></td><td><?= esc($log['operating_system'] ?: 'Unknown') ?> · <?= esc($log['browser'] ?: 'Unknown') ?> <?= esc($log['browser_version'] ?: '') ?><br><span class="muted"><?= esc($log['device_type']) ?></span></td><td><a href="<?= site_url('admin/audit-logs') . '?event=' . urlencode($log['event']) . '&reference=' . urlencode((string) $log['reference']) ?>">Filter</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
  <?php $query = http_build_query(array_filter($filters, static fn ($value) => $value !== '')); ?><div class="pager"><span>Page <?= (int) $page ?> of <?= (int) $totalPages ?></span><span><?php if ($page > 1): ?><a href="<?= site_url('admin/audit-logs') . '?' . $query . ($query ? '&' : '') . 'page=' . ($page - 1) ?>">← Previous</a><?php endif; ?><?php if ($page < $totalPages): ?><a href="<?= site_url('admin/audit-logs') . '?' . $query . ($query ? '&' : '') . 'page=' . ($page + 1) ?>">Next →</a><?php endif; ?></span></div>
</div></main></div></body></html>
