<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login history · UIU Recruitment Portal Admin</title>
  <?php $adminSection = 'login-history'; ?><?= $this->include('admin/_styles') ?>
  <style>.audit-filters{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:20px}.audit-filters input,.audit-filters select{height:38px;border:1px solid #dfe4ec;border-radius:8px;padding:0 10px;background:#fff;font:inherit}.filter-actions{display:flex;gap:8px;align-items:center}.filter-actions button{height:38px;border:0;border-radius:8px;padding:0 15px;background:#168fd4;color:#fff;font-weight:600}.filter-actions a{color:#168fd4;font-size:13px}.status{display:inline-block;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:700}.success{background:#eaf8ef;color:#187345}.failed{background:#fff0f0;color:#a32121}.muted{color:#798196;font-size:12px}.pager{display:flex;justify-content:space-between;align-items:center;margin-top:16px;color:#69778d;font-size:13px}.pager a{color:#168fd4;font-weight:700;margin-left:12px}@media(max-width:900px){.audit-filters{grid-template-columns:repeat(2,1fr)}}@media(max-width:550px){.audit-filters{grid-template-columns:1fr}}\n+  </style>
</head>
<body><div class="admin-app"><?php $username=session()->get('admin_username');$usertype=session()->get('admin_usertype'); ?><?= $this->include('admin/_sidebar') ?><main class="admin-main"><header class="admin-topbar"><div class="admin-top-title">Login history</div><div class="admin-search">⌕ <span>Search...</span><span style="margin-left:auto">⌘ K</span></div><div class="admin-pill">✦ Authentication trail</div></header><div class="admin-content">
  <div class="admin-heading"><div><h1>Login history</h1><p>Successful and failed authentication attempts. Passwords and tokens are never stored.</p></div><a class="admin-btn" href="<?= site_url('admin/audit-logs') ?>">Audit logs</a></div>
  <form class="audit-filters" method="get" action="<?= site_url('admin/login-history') ?>">
    <input type="date" name="date_from" value="<?= esc($filters['dateFrom']) ?>"><input type="date" name="date_to" value="<?= esc($filters['dateTo']) ?>"><input name="user" placeholder="User / login identifier" value="<?= esc($filters['user']) ?>"><select name="status"><option value="">All statuses</option><option value="SUCCESS" <?= $filters['status'] === 'SUCCESS' ? 'selected' : '' ?>>SUCCESS</option><option value="FAILED" <?= $filters['status'] === 'FAILED' ? 'selected' : '' ?>>FAILED</option></select><input name="ip" placeholder="IP address" value="<?= esc($filters['ip']) ?>"><select name="device"><option value="">All devices</option><?php foreach (['Desktop','Mobile','Tablet','Bot','Unknown'] as $device): ?><option value="<?= $device ?>" <?= $filters['device'] === $device ? 'selected' : '' ?>><?= $device ?></option><?php endforeach; ?></select><input name="browser" placeholder="Browser" value="<?= esc($filters['browser']) ?>"><div class="filter-actions"><button type="submit">Search</button><a href="<?= site_url('admin/login-history') ?>">Reset</a></div>
  </form>
  <?php if (!$logs): ?><div class="admin-card admin-empty">No login history found.</div><?php else: ?><div class="admin-table"><table><thead><tr><th>Date &amp; time</th><th>User / identifier</th><th>Status</th><th>Failure reason</th><th>IP address</th><th>Browser / OS</th><th>Device</th><th>Logout time</th></tr></thead><tbody><?php foreach ($logs as $log): ?><tr><td><?= esc(date('d M Y · h:i:s A', strtotime($log['created_at']))) ?></td><td><strong><?= esc($log['user_name'] ?: ($log['username'] ?: ($log['login_identifier'] ?: 'Unknown'))) ?></strong><?php if ($log['login_identifier']): ?><br><span class="muted"><?= esc($log['login_identifier']) ?></span><?php endif; ?></td><td><span class="status <?= $log['status'] === 'SUCCESS' ? 'success' : 'failed' ?>"><?= esc($log['status']) ?></span></td><td><?= esc($log['failure_reason'] ?: '—') ?></td><td><?= esc($log['ip_address'] ?: '—') ?></td><td><?= esc($log['browser'] ?: 'Unknown') ?> <?= esc($log['browser_version'] ?: '') ?><br><span class="muted"><?= esc($log['operating_system'] ?: 'Unknown') ?></span></td><td><?= esc($log['device_type']) ?></td><td><?= esc($log['logged_out_at'] ? date('d M Y · h:i:s A', strtotime($log['logged_out_at'])) : '—') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
  <?php $query = http_build_query(array_filter($filters, static fn ($value) => $value !== '')); ?><div class="pager"><span>Page <?= (int) $page ?> of <?= (int) $totalPages ?></span><span><?php if ($page > 1): ?><a href="<?= site_url('admin/login-history') . '?' . $query . ($query ? '&' : '') . 'page=' . ($page - 1) ?>">← Previous</a><?php endif; ?><?php if ($page < $totalPages): ?><a href="<?= site_url('admin/login-history') . '?' . $query . ($query ? '&' : '') . 'page=' . ($page + 1) ?>">Next →</a><?php endif; ?></span></div>
</div></main></div></body></html>
